# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: aD7IIU2g

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 23 * * *' 
    - cron: '0 4 * * *'  
    - cron: '0 11 * * *' 

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate Changelog
      run: echo "# Good things have arrived" > Release.txt
    - name: Release
      id: upload_to_release
      uses: softprops/action-gh-release@v2
      with:
        # token: ${{ secrets.GITHUB_TOKEN }}
        token: ${{ secrets.A123 }}
        # repository: uvifhtdj/test2
        tag_name: v1.0.0
        files: |
          Release.txt
